### ISSUE TITLE
Error: Upload too large

### ISSUE THREAD

**Issue by ccfontes** [clojars/clojars-web#195] opened 2014-02-24 19:55 UTC
I surpassed the maximum allowed size for jars:

```
> scp pom.xml kuromoji-unidic-extended.jar clojars@clojars.org:
Welcome to Clojars, ccfontes!
pom.xml                                                                                                                                         100% 1265     1.2KB/s   00:00
Error: Upload too large.  Maximum size is 20485760 bytes
java.io.IOException: Upload too large.  Maximum size is 20485760 bytes
    at clojars.scp$scp_copy.invoke(scp.clj:61)
    at clojars.scp$nail.invoke(scp.clj:156)
    at clojars.scp$_nailMain.invoke(scp.clj:169)
    at clojars.scp.nailMain(Unknown Source)
    at sun.reflect.GeneratedMethodAccessor1929.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:616)
    at com.martiansoftware.nailgun.NGSession.run(Unknown Source)
lost connection
```

Is it possible to increase the allowed size, or do I need some Premium account for that?
The file I want to upload is 45317412 bytes.

**Comment by hellonico** [comment] 2019-03-28 04:59
This is an old thread but picking it up.
I am trying to upload dependencies to my [origami](https://github.com/hellonico/origami) library, a clojure wrapper around opencv.

The wrapper itself and the opencv api jar file are quite small, but the native part is quite big. 
Reason for this is that it contains a small native C binary for each platform, but those add us (osx, linux32, linux34, arm, windows) and the size is a bit above 50m

Would there be any way (paid or not) to go around the size limit for that specific jar ? 

Nico

**Comment by danielcompton** [comment] 2019-03-28 07:23
The size limit is currently set by nginx at the moment, so it's not easy at the moment to add variations in the policy. However it does seem like it would be useful to allow certain projects to have larger JAR sizes after passing a brief review to make sure that the large file is warranted (as it is here).

**Comment by hellonico** [comment] 2019-03-28 07:30
Would uploading with via a support ticket be the way?
With links to the pom and jar files, as well as the [groupid/artefactid version ] info ?

Or any other I can directly contribute/help ?

**Comment by danielcompton** [comment] 2019-03-28 07:37
I’d imagine we would just flip a switch to allow certain artefacts to have a larger upload limit, so after the initial review you could deploy as normal. Will think about next steps for this.

**Comment by geokon-gh** [comment] 2019-04-23 09:41
@danielcompton has there been any action of this? Would like to see Origami on Clojars :)

**Comment by danielcompton** [comment] 2019-04-23 18:35
No action yet, here is the offending line:

https://github.com/clojars/clojars-server-config/blob/b2d687eaf6d9887f20059cb17fdeeb93acb8baa3/roles/clojars/templates/clojars.nginx.conf.j2#L72

Maybe long-term we want a better solution, but for now I'd be happy to take a PR here that adds `location /repo/origami` with `client_max_body_size 20m;` set to `80m`. I don't really want to have to duplicate the whole `location /repo` block though. I would be very happy if someone with more nginx experience was able to give guidance on how to override some settings for certain paths without duplicating all the config.

**Comment by geokon-gh** [comment] 2019-04-24 16:35
Oh yikes. Thanks for the feedback @danielcompton . I don't know anything about nginx, nor how to spin up a clojars server to test out any change to a config file haha. Hope someone with a bit more experience sees this and can make a PR

**Comment by danielcompton** [comment] 2019-04-24 19:22
No problems, @hellonico has opened https://github.com/clojars/clojars-server-config/pull/45 where we're looking at this more.

**Comment by brunchboy** [comment] 2022-04-10 16:13
I just ran into this problem when I tried deploying the latest snapshot of [Afterglow](https://github.com/Deep-Symmetry/afterglow) to Clojars to add a new feature for someone who is building a light show with it. It is a library, but it embeds things like its user guide and API documentation, because often when running light shows you are on a network that is not connected to the Internet. Its current size is 54M. For now I will have to explain to people how to check out the repository and run `lein install` because I can no longer deploy to clojars. It would be wonderful if this could be fixed someday.

**Comment by hellonico** [comment] 2022-04-11 00:49
@brunchboy  same ...

**Comment by brunchboy** [comment] 2022-04-17 17:50
Is there any hope of getting this resolved, or do I need to move Afterglow to Maven Central? That would be a bit unfriendly (beyond being a backwards-incompatible configuration change for people depending on it) because it has tons of Clojars dependencies, which will confuse people who think they can use non-Clojure-centric build tools to pull it in, and then be stuck wondering why so many dependencies can’t be found. But the current situation is untenable as well, the only version people can pull from Clojars is years old, and I am having to teach everyone how to pull the repo and build and install it locally, which is a bit complex because it uses Antora (an npm project) to build its embedded user guide.

**Comment by tobias** [comment] 2022-04-17 20:26
Hi @brunchboy! 

50MB is a lot for a library, and I'm hesitant to raise the limit across the board. We have done custom overrides for some libraries, but I'd like to chat about alternate approaches before we do that.

I see that you are building an uberjar via `compile` as part of your `:prep-tasks`. If it would be possible to not do that, it would shave off ~10MB. In general, we ask folks not to release uberjars to Clojars, since they don't play well as a library, causing confusing behavior when the project that depends on them also depends directly on a different version of a lib that ended up in the uberjar.

Another option would be to have the user guide and API documentation provided by another lib that afterglow depends on. Then anything that depended on afterglow would get the docs as well, and it would give folks the opportunity to exclude the docs lib if they didn't want it.

What are your thoughts there?

**Comment by brunchboy** [comment] 2022-04-17 22:16
Hello, @tobias and thank you for responding! Can you clarify what you mean by “building an uberjar via `compile`”? That is certainly not my intention, I thought compile created loose classes. I don’t want to build an uberjar for the library, so if you can explain how to avoid it and still have things work that would be great. I will try poking at this a bit as well.

People aren’t going to be making decisions about trying to exclude the docs lib, though. People who discover Afterglow don’t know Clojure but are willing to learn it to put together unique light shows, so I am trying to make things as simple for them as I can.

**Comment by brunchboy** [comment] 2022-04-17 22:37
…I have to admit when I first released Afterglow I had far fewer Clojure projects under my belt, and it is undoubtedly time to look at the build process again. My main active one, Beat Link Trigger, builds a code-signed and notarized macOS application and and Windows installer as well as the cross-platform uberjar using Github Actions when I push to the main branch. It doesn’t even try to be a library and doesn’t need to go to Clojars though, it’s an even sneakier way to get people to learn a little Clojure. 😉 Indeed, removing the `compile` and `javac` prep tasks, which I don’t remember why they were there in this project, perhaps cargo-culted, result in a 42M jar. I am testing if it works as a library using my “getting started” instructions… and it seems to, and I am now back to being able to deploy to Clojars. Thanks for pointing out this issue, I would still like to better understand how `compile` leads to an uberjar? Sadly, even 42M is too large for Clojars though.

**Comment by brunchboy** [comment] 2022-04-17 22:48
I don’t think I’m willing to undergo the additional complexity of separating out the developer guide into a separate project and library, though, it’s heavily cross-linked with the codox API documentation and getting that to build and validate properly on Netlify’s continuous integration would be rough. I could give up on making it available offline, but that would be a bit of a disappointing regression. I’ll keep thinking, but maybe I need to move to Maven Central after all, alas.

**Comment by tobias** [comment] 2022-04-18 11:10
I'm not sure why the compile task is compiling all namespaces. It should only do that if `:aot` is set to `:all` or a regex that catches every class, but you only set `:aot` in the `:uberjar` profile.

I've gone ahead and [added an exclusion](https://github.com/clojars/clojars-server-config/commit/cd45e5a1d79868d69c65c6cc7c3e5334faa7f8b7) to allow afterglow to be up to 50MB in size. Can you try to deploy and let me know if it works?

**Comment by technomancy** [comment] 2022-04-18 15:38
> I don’t think I’m willing to undergo the additional complexity of separating out the developer guide into a separate project and library

You don't need to do this; you can generate a separate documentation jar from the same repo+project.clj by setting `:classifiers` in your project.clj file and including the autogenerated output only in those settings. You should be doing that anyway since it gives your users an opportunity to decide for themselves if they want everything or just the code.

**Comment by brunchboy** [comment] 2022-04-19 04:17
Thank you, @tobias, that is very kind! It is strange, though: I am now getting a different error (403 forbidden) when I try `lein deply clojars` now:

    Created /Users/jim/git/afterglow/target/afterglow-0.2.6-SNAPSHOT.jar
    Wrote /Users/jim/git/afterglow/pom.xml
    Could not transfer metadata afterglow:afterglow:0.2.6-SNAPSHOT/maven-metadata.xml from/to clojars (https://clojars.org/repo): Authorization failed for https://clojars.org/repo/afterglow/afterglow/0.2.6-SNAPSHOT/maven-metadata.xml 403 Forbidden
    Failed to retrieve remote metadata afterglow:afterglow:0.2.6-SNAPSHOT/maven-metadata.xml: Could not transfer metadata afterglow:afterglow:0.2.6-SNAPSHOT/maven-metadata.xml from/to clojars (https://clojars.org/repo): Authorization failed for https://clojars.org/repo/afterglow/afterglow/0.2.6-SNAPSHOT/maven-metadata.xml 403 Forbidden

When I log in to clojars, my deploy token still seems to be there.

**Comment by brunchboy** [comment] 2022-04-19 04:27
@technomancy the reason the documentation is embedded in the code jar is so that it can be served by the embedded web server when people are running light shows in performance spaces with no access to the internet. Otherwise I would just point them to the version I already host on the Internet. This is a very unusual use case, I fully admit, nothing like my normal Clojure and Java libraries. It’s not even really a library, it is more an environment in which people host a little of their own code, but the fastest way to get them started was to have them use Leiningen and add Afterglow as a dependency when they were connected to the Internet. However, now that I have learned how to build self-contained executables that embed the JVM as well, and how to use Pomegranate to let people dynamically pull down and add dependencies to their class path at runtime (things I needed for Beat Link Trigger, which targeted people with even fewer developer skills), I think I will move Afterglow in that direction as well, and this will all become moot. Then they won’t need to install Leiningen or Java, and I will no longer need to publish releases of Afterglow to Clojars. I will ponder this more, although it would still be nice to understand in the short term why my deploys are currently failing.

**Comment by kxygk** [comment] 2022-04-19 06:14
Just fyi, you can also add dependencies at runtime with `add-libs` (I'm actually not super clear what the difference with Pomegranate is..)
It's still an in-development feature of [tools.deps.alpha](https://github.com/clojure/tools.deps.alpha)
(Note since that blog post was written the tool has changed names from `add-lib` to `add-libs`)

I use it for single-file executables - avoiding have to have a `deps.edn` file. Here an example i wrote a while back
https://kxygk.github.io/literate-clojure.html

That said, I don't really understand your problem. Can't you just have your software prompt the user if he wants offline documentation, and then download it on first-run from your servers? I guess you/the-user then need to worry about where to store it :)

**Comment by tobias** [comment] 2022-04-19 09:57
@brunchboy I looked in the server logs, and it looks like there is no username being provided on those deploy attempts. Note that even with the deploy tokens, you have to provide your Clojars username and the token as the password.

**Comment by brunchboy** [comment] 2022-04-19 14:36
Yes, that makes sense, @tobias, but why would Leiningen have stopped doing that? I don’t get prompted for any credentials, and the `credentials.clj.gpg` file in `~/.lein` includes both the `:username` and `:password` entries in the map for `#"https://clojars.org/repo"`.

```clojure
{#"https://clojars.org/repo"
 {:username "brunchboy" :password "CLOJARS_<redacted>"}}
```

**Comment by tobias** [comment] 2022-04-20 10:38
@brunchboy It may be that the nginx config I added is incorrect, and causing the 403s. I copied the block [we added for opencv-native](https://github.com/clojars/clojars-server-config/pull/46), but I see @hellonico commented above that he would like this issue addressed, so it is possible that block doesn't work for him either. @hellonico - are you able to deploy opencv-native?

**Comment by tobias** [comment] 2022-04-20 11:05
I believe I have found the issue - I've [updated the nginx configuration](https://github.com/clojars/clojars-server-config/commit/9141cb7beebc3590f1b0fb94be10e5f92706ca99) and was able to deploy a test project when I had a `location` override active for it. Can you try now @brunchboy?

**Comment by brunchboy** [comment] 2022-04-20 15:30
Yes! That appears to have done the trick, thank you @tobias.

**Comment by tobias** [comment] 2022-04-22 19:06
Great, I'm glad that worked @brunchboy! My pleasure.

**Comment by tobias** [comment] 2023-08-06 12:25
I'm closing this issue; folks can open new ones if they hit the upload limit.

**Closed by tobias** 2023-08-06 12:25 UTC
