### ISSUE TITLE
Problem with Clojars dropping / ignoring some artifacts?

### ISSUE THREAD

**Issue by mikera** [clojars/clojars-web#532] opened 2016-06-08 21:59 UTC
Hi,

I've been hitting problems releasing core.matrix to Clojars - it seems to be dropping the test jars that previously uploaded fine. Compare:
https://clojars.org/repo/net/mikera/core.matrix/0.52.1/

With the older release:
https://clojars.org/repo/net/mikera/core.matrix/0.50.0/

As you can see, the older release included a lot more artifacts. I'm pretty sure the artifacts all got uploaded as reported by Maven:
`      Uploaded: https://clojars.org/repo/net/mikera/core.matrix/0.52.1/core.matrix-0.52.1-tests.jar (63 KB at 28.8 KB/sec)`

So it appears that the Artifacts are now being dropped by Clojars at some point.

**Comment by danielcompton** [comment] 2016-06-08 22:04
This is likely related to #226, and #505. Toby is more familiar with that change.

**Comment by tobias** [comment] 2016-06-09 12:25
This is indeed related to #226 and #505, and is the same root cause as #515.

We currently use the upload of `maven-metadata.xml` as a signal to
close the interim repo, but that's clearly not the correct thing to
do. I had assumed uploading artifacts after the `maven-metadata.xml`
file only occurred when using `maven-deploy-plugin` from the command
line, but it looks like maven always does that with classified
artifacts:

```
::ffff:86.17.77.141 - mikera [08/Jun/2016:21:52:04 +0000] "PUT /repo/net/mikera/core.matrix/0.52.1/core.matrix-0.52.1.jar HTTP/1.1" 201 0 "-" "Apache-Maven/3.3.3 (Java 1.8.0_40; Windows 8.1 6.3)"                                                                                     
::ffff:86.17.77.141 - mikera [08/Jun/2016:21:52:05 +0000] "PUT /repo/net/mikera/core.matrix/0.52.1/core.matrix-0.52.1.jar.sha1 HTTP/1.1" 201 0 "-" "Apache-Maven/3.3.3 (Java 1.8.0_40; Windows 8.1 6.3)"                                                                                
::ffff:86.17.77.141 - mikera [08/Jun/2016:21:52:05 +0000] "PUT /repo/net/mikera/core.matrix/0.52.1/core.matrix-0.52.1.jar.md5 HTTP/1.1" 201 0 "-" "Apache-Maven/3.3.3 (Java 1.8.0_40; Windows 8.1 6.3)"                                                                                 
::ffff:86.17.77.141 - mikera [08/Jun/2016:21:52:06 +0000] "PUT /repo/net/mikera/core.matrix/0.52.1/core.matrix-0.52.1.pom HTTP/1.1" 201 0 "-" "Apache-Maven/3.3.3 (Java 1.8.0_40; Windows 8.1 6.3)"                                                                                     
::ffff:86.17.77.141 - mikera [08/Jun/2016:21:52:07 +0000] "PUT /repo/net/mikera/core.matrix/0.52.1/core.matrix-0.52.1.pom.sha1 HTTP/1.1" 201 0 "-" "Apache-Maven/3.3.3 (Java 1.8.0_40; Windows 8.1 6.3)"                                                                                
::ffff:86.17.77.141 - mikera [08/Jun/2016:21:52:07 +0000] "PUT /repo/net/mikera/core.matrix/0.52.1/core.matrix-0.52.1.pom.md5 HTTP/1.1" 201 0 "-" "Apache-Maven/3.3.3 (Java 1.8.0_40; Windows 8.1 6.3)"                                                                                 
::ffff:86.17.77.141 - mikera [08/Jun/2016:21:52:10 +0000] "PUT /repo/net/mikera/core.matrix/maven-metadata.xml HTTP/1.1" 201 0 "-" "Apache-Maven/3.3.3 (Java 1.8.0_40; Windows 8.1 6.3)"                                                                                                
::ffff:86.17.77.141 - mikera [08/Jun/2016:21:52:11 +0000] "PUT /repo/net/mikera/core.matrix/maven-metadata.xml.sha1 HTTP/1.1" 201 0 "-" "Apache-Maven/3.3.3 (Java 1.8.0_40; Windows 8.1 6.3)"                                                                                           
::ffff:86.17.77.141 - mikera [08/Jun/2016:21:52:11 +0000] "PUT /repo/net/mikera/core.matrix/maven-metadata.xml.md5 HTTP/1.1" 201 0 "-" "Apache-Maven/3.3.3 (Java 1.8.0_40; Windows 8.1 6.3)"                                                                                            
::ffff:86.17.77.141 - mikera [08/Jun/2016:21:52:13 +0000] "PUT /repo/net/mikera/core.matrix/0.52.1/core.matrix-0.52.1-sources.jar HTTP/1.1" 201 0 "-" "Apache-Maven/3.3.3 (Java 1.8.0_40; Windows 8.1 6.3)"                                                                             
::ffff:86.17.77.141 - mikera [08/Jun/2016:21:52:13 +0000] "PUT /repo/net/mikera/core.matrix/0.52.1/core.matrix-0.52.1-sources.jar.sha1 HTTP/1.1" 201 0 "-" "Apache-Maven/3.3.3 (Java 1.8.0_40; Windows 8.1 6.3)"                                                                        
::ffff:86.17.77.141 - mikera [08/Jun/2016:21:52:14 +0000] "PUT /repo/net/mikera/core.matrix/0.52.1/core.matrix-0.52.1-sources.jar.md5 HTTP/1.1" 201 0 "-" "Apache-Maven/3.3.3 (Java 1.8.0_40; Windows 8.1 6.3)"                                                                         
::ffff:86.17.77.141 - mikera [08/Jun/2016:21:52:15 +0000] "PUT /repo/net/mikera/core.matrix/0.52.1/core.matrix-0.52.1-javadoc.jar HTTP/1.1" 201 0 "-" "Apache-Maven/3.3.3 (Java 1.8.0_40; Windows 8.1 6.3)"                                                                             
::ffff:86.17.77.141 - mikera [08/Jun/2016:21:52:15 +0000] "PUT /repo/net/mikera/core.matrix/0.52.1/core.matrix-0.52.1-javadoc.jar.sha1 HTTP/1.1" 201 0 "-" "Apache-Maven/3.3.3 (Java 1.8.0_40; Windows 8.1 6.3)"                                                                        
::ffff:86.17.77.141 - mikera [08/Jun/2016:21:52:16 +0000] "PUT /repo/net/mikera/core.matrix/0.52.1/core.matrix-0.52.1-javadoc.jar.md5 HTTP/1.1" 201 0 "-" "Apache-Maven/3.3.3 (Java 1.8.0_40; Windows 8.1 6.3)"                                                                         
::ffff:86.17.77.141 - mikera [08/Jun/2016:21:52:17 +0000] "PUT /repo/net/mikera/core.matrix/0.52.1/core.matrix-0.52.1-tests.jar HTTP/1.1" 201 0 "-" "Apache-Maven/3.3.3 (Java 1.8.0_40; Windows 8.1 6.3)"                                                                               
::ffff:86.17.77.141 - mikera [08/Jun/2016:21:52:18 +0000] "PUT /repo/net/mikera/core.matrix/0.52.1/core.matrix-0.52.1-tests.jar.sha1 HTTP/1.1" 201 0 "-" "Apache-Maven/3.3.3 (Java 1.8.0_40; Windows 8.1 6.3)"                                                                          
::ffff:86.17.77.141 - mikera [08/Jun/2016:21:52:18 +0000] "PUT /repo/net/mikera/core.matrix/0.52.1/core.matrix-0.52.1-tests.jar.md5 HTTP/1.1" 201 0 "-" "Apache-Maven/3.3.3 (Java 1.8.0_40; Windows 8.1 6.3)"                                                                           
::ffff:86.17.77.141 - mikera [08/Jun/2016:21:52:19 +0000] "PUT /repo/net/mikera/core.matrix/0.52.1/core.matrix-0.52.1.jar.asc HTTP/1.1" 201 0 "-" "Apache-Maven/3.3.3 (Java 1.8.0_40; Windows 8.1 6.3)"                                                                                 
::ffff:86.17.77.141 - mikera [08/Jun/2016:21:52:19 +0000] "PUT /repo/net/mikera/core.matrix/0.52.1/core.matrix-0.52.1.pom.asc HTTP/1.1" 201 0 "-" "Apache-Maven/3.3.3 (Java 1.8.0_40; Windows 8.1 6.3)"                                                                                 
::ffff:86.17.77.141 - mikera [08/Jun/2016:21:52:20 +0000] "PUT /repo/net/mikera/core.matrix/0.52.1/core.matrix-0.52.1-sources.jar.asc HTTP/1.1" 201 0 "-" "Apache-Maven/3.3.3 (Java 1.8.0_40; Windows 8.1 6.3)"
::ffff:86.17.77.141 - mikera [08/Jun/2016:21:52:21 +0000] "PUT /repo/net/mikera/core.matrix/0.52.1/core.matrix-0.52.1-javadoc.jar.asc HTTP/1.1" 201 0 "-" "Apache-Maven/3.3.3 (Java 1.8.0_40; Windows 8.1 6.3)"                                                                         
::ffff:86.17.77.141 - mikera [08/Jun/2016:21:52:21 +0000] "PUT /repo/net/mikera/core.matrix/0.52.1/core.matrix-0.52.1-tests.jar.asc HTTP/1.1" 201 0 "-" "Apache-Maven/3.3.3 (Java 1.8.0_40; Windows 8.1 6.3)"
```

I have a fix in mind that I will try to get implemented today - sorry for the trouble.

**Comment by tobias** [comment] 2016-06-10 16:05
I have a fix for this on master - I need to schedule a maintenance window to deploy it, since there are other changes in the pipe that require db migration. I'll try to make that happen early next week.

**Comment by mikera** [comment] 2016-06-14 08:38
Awesome thanks @tobias ! Will save me a lot of time vs. having to manually copy snapshots around!

**Comment by tobias** [comment] 2016-06-15 21:32
@mikera - I tried to deploy this fix earlier this week, but had to roll it back due to unrelated issues. I'm fixing those now, and hope to try again early next week.

**Comment by tobias** [comment] 2016-06-21 02:24
@mikera - this should now be fixed. I deployed a fork of `core.matrix`, and can see the test artifacts there: https://clojars.org/repo/org/clojars/tcrawley/core.matrix/0.52.4-SNAPSHOT/

I'm closing this, but feel free to reopen if you see any issues.

**Closed by tobias** 2016-06-21 02:24 UTC
Labels: bug
