### ISSUE TITLE
503, ReasonPhrase: Service Temporarily Unavailable

### ISSUE THREAD

**Issue by peter** [clojars/clojars-web#550] opened 2016-08-04 14:39 UTC
http://status.clojars.org says all systems are operational but I keep getting a 503 on deploy.

<details>
<summary>

Deploy log</summary>

```
peter.marklund@C02MM634F6T6 ~/src/versioned]$ lein deploy clojars
No credentials found for clojars
See `lein help deploying` for how to configure credentials to avoid prompts.
Username: peter@marklunds.com
Password: 
Warning: The Main-Class specified does not exist within the jar. It may not be executable as expected. A gen-class directive may be missing in the namespace which contains the main method.
Created /Users/peter.marklund/src/versioned/target/versioned-0.2.0.jar
Wrote /Users/peter.marklund/src/versioned/pom.xml
Sending versioned/versioned/0.2.0/versioned-0.2.0.jar (819k)
    to https://clojars.org/repo/
Could not transfer artifact versioned:versioned:jar:0.2.0 from/to clojars (https://clojars.org/repo/): Failed to transfer file: https://clojars.org/repo/versioned/versioned/0.2.0/versioned-0.2.0.jar. Return code is: 503, ReasonPhrase: Service Temporarily Unavailable.
Sending versioned/versioned/0.2.0/versioned-0.2.0.pom (4k)
    to https://clojars.org/repo/
Could not transfer artifact versioned:versioned:pom:0.2.0 from/to clojars (https://clojars.org/repo/): Failed to transfer file: https://clojars.org/repo/versioned/versioned/0.2.0/versioned-0.2.0.pom. Return code is: 401, ReasonPhrase: Unauthorized.
Failed to deploy artifacts: Could not transfer artifact versioned:versioned:jar:0.2.0 from/to clojars (https://clojars.org/repo/): Failed to transfer file: https://clojars.org/repo/versioned/versioned/0.2.0/versioned-0.2.0.jar. Return code is: 503, ReasonPhrase: Service Temporarily Unavailable.
peter.marklund@C02MM634F6T6 ~/src/versioned]$ lein deploy clojars
No credentials found for clojars
See `lein help deploying` for how to configure credentials to avoid prompts.
Username: peter@marklunds.com
Password: 
Warning: The Main-Class specified does not exist within the jar. It may not be executable as expected. A gen-class directive may be missing in the namespace which contains the main method.
Created /Users/peter.marklund/src/versioned/target/versioned-0.2.0.jar
Wrote /Users/peter.marklund/src/versioned/pom.xml
Sending versioned/versioned/0.2.0/versioned-0.2.0.jar (819k)
    to https://clojars.org/repo/
Could not transfer artifact versioned:versioned:jar:0.2.0 from/to clojars (https://clojars.org/repo/): Failed to transfer file: https://clojars.org/repo/versioned/versioned/0.2.0/versioned-0.2.0.jar. Return code is: 503, ReasonPhrase: Service Temporarily Unavailable.
Sending versioned/versioned/0.2.0/versioned-0.2.0.pom (4k)
    to https://clojars.org/repo/
Could not transfer artifact versioned:versioned:pom:0.2.0 from/to clojars (https://clojars.org/repo/): Failed to transfer file: https://clojars.org/repo/versioned/versioned/0.2.0/versioned-0.2.0.pom. Return code is: 401, ReasonPhrase: Unauthorized.
Failed to deploy artifacts: Could not transfer artifact versioned:versioned:jar:0.2.0 from/to clojars (https://clojars.org/repo/): Failed to transfer file: https://clojars.org/repo/versioned/versioned/0.2.0/versioned-0.2.0.jar. Return code is: 503, ReasonPhrase: Service Temporarily Unavailable.
peter.marklund@C02MM634F6T6 ~/src/versioned]$ lein deploy clojars
No credentials found for clojars
See `lein help deploying` for how to configure credentials to avoid prompts.
Username: peter@marklunds.com
Password: 
Warning: The Main-Class specified does not exist within the jar. It may not be executable as expected. A gen-class directive may be missing in the namespace which contains the main method.
Created /Users/peter.marklund/src/versioned/target/versioned-0.2.0.jar
Wrote /Users/peter.marklund/src/versioned/pom.xml
Sending versioned/versioned/0.2.0/versioned-0.2.0.jar (819k)
    to https://clojars.org/repo/
Could not transfer artifact versioned:versioned:jar:0.2.0 from/to clojars (https://clojars.org/repo/): Failed to transfer file: https://clojars.org/repo/versioned/versioned/0.2.0/versioned-0.2.0.jar. Return code is: 503, ReasonPhrase: Service Temporarily Unavailable.
Sending versioned/versioned/0.2.0/versioned-0.2.0.pom (4k)
    to https://clojars.org/repo/
Could not transfer artifact versioned:versioned:pom:0.2.0 from/to clojars (https://clojars.org/repo/): Failed to transfer file: https://clojars.org/repo/versioned/versioned/0.2.0/versioned-0.2.0.pom. Return code is: 401, ReasonPhrase: Unauthorized.
Failed to deploy artifacts: Could not transfer artifact versioned:versioned:jar:0.2.0 from/to clojars (https://clojars.org/repo/): Failed to transfer file: https://clojars.org/repo/versioned/versioned/0.2.0/versioned-0.2.0.jar. Return code is: 503, ReasonPhrase: Service Temporarily Unavailable.
peter.marklund@C02MM634F6T6 ~/src/versioned]$ date
Thu Aug  4 16:37:39 CEST 2016
peter.marklund@C02MM634F6T6 ~/src/versioned]$ 
```

</details>

**Comment by hamhut1066** [comment] 2016-08-04 14:59
Odd, seems to give you a 403 on the second request...

having a look here:
https://clojars.org/repo/versioned/versioned/
it seems that the directory isn't being created.

It looks like your second error is coming up here:
https://github.com/clojars/clojars-web/blob/2c7fd8ac8c9c2d206f30868f1549246d50278d2e/src/clojars/routes/repo.clj#L345

As it's catching all Exceptions, it's not possible to get any information about what is actually happening.

But looking into the finalize-deploy function:
The most likely thing looks like:
https://github.com/clojars/clojars-web/blob/2c7fd8ac8c9c2d206f30868f1549246d50278d2e/src/clojars/routes/repo.clj#L240

ie. you're _pom_ file may be invalid.

I suggest creating a sample project and uploading to into your user group, and seeing if that works.

**Comment by tobias** [comment] 2016-08-04 15:08
This looks like it may be related to or similar to #72 - in the nginx error log, I see:

```
2016/08/04 14:29:06 [error] 3249#0: *23099157 writev() failed (32: Broken pipe) while sending request to upstream, client: ::ffff:2.71.33.229, server: clojars.org, request: "PUT /repo/versioned/versioned/0.2.0/versioned-0.2.0.jar HTTP/1.1", upstream: "http://127.0.0.1:8001/repo/versioned/versioned/0.2.0/versioned-0.2.0.jar", host: "clojars.org"
```

But see no errors from the clojars jvm process. Other deploys seem to be working fine, so I suspect whatever the underlying error is may be related to the size of the jar. I've restarted the clojars process, can you try the deploy again?

**Comment by tobias** [comment] 2016-08-04 15:27
@hamhut1066 I'm not sure where that 401 on the pom is coming from - https://github.com/clojars/clojars-web/blob/2c7fd8ac8c9c2d206f30868f1549246d50278d2e/src/clojars/routes/repo.clj#L345 can only happen when a `maven-metadata.xml` file is uploaded. And I think the only thing that will return a 401 for us is friend. But I think the 401 is a red herring, the cause of the broken connection between nginx and the clojars process is the real error here.

**Comment by tobias** [comment] 2016-10-09 01:13
@peter - could you try the same steps again and see if you still get the error? We've moved clojars to a new machine that has a newer version of linux and is on a different hypervisor implementation. I'm curious to know if something there may have fixed this issue.

**Comment by tobias** [comment] 2020-04-04 13:05
Closing this since there hasn't been a response in several years.

**Closed by tobias** 2020-04-04 13:05 UTC

**Comment by anshbansal** [comment] 2020-04-28 05:36
This happened with me today

```
➜  clojure-noob ../lein.sh run
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
Could not transfer artifact nrepl:nrepl:pom:0.6.0 from/to clojars (https://repo.clojars.org/): Failed to transfer file: https://repo.clojars.org/nrepl/nrepl/0.6.0/nrepl-0.6.0.pom. Return code is: 503 , ReasonPhrase:Backend unavailable, connection timeout.
This could be due to a typo in :dependencies, file system permissions, or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
```
I am not behind any proxy. I had opened https://repo.clojars.org/ in Google Chrome and saw 503 Error. Although after a while it did show up.
