### ISSUE TITLE
Artifacts groupId not being populated correctly in Clojars feed

### ISSUE THREAD

**Issue by mikera** [clojars/clojars-web#232] opened 2014-07-21 12:14 UTC
I've noticed that some of my projects aren't getting correct information in the Clojars feed, for example core.matrix is missing the groupId:

```
{:versions ["0.26.0" "0.25.0" "0.24.0" "0.23.0" "0.22.0" "0.21.0" "0.20.0" "0.19.0" "0.18.0" "0.17.0" "0.16.0" "0.15.0" "0.14.0" "0.13.1" "0.13.0" "0.12.0" "0.11.0" "0.10.0" "0.9.0" "0.8.0" "0.7.2" "0.7.1" "0.7.0" "0.6.0" "0.5.0" "0.4.1" "0.4.0" "0.3.0" "0.2.0" "0.1.1" "0.1.0" "0.0.12" "0.0.11" "0.0.10"], 
:scm {:connection "scm:git:git@github.com:clojure-numerics/core.matrix.git", :url "scm:git:git@github.com:clojure-numerics/core.matrix.git", :developer-connection "scm:git:git@github.com:clojure-numerics/core.matrix.git", :tag "core.matrix-0.26.0"}, 
:artifact-id "core.matrix"}
```

I suspect this is an issue may be related to the fact that the pom is inheriting the groupId from a parent pom?

**Comment by mynomoto** [comment] 2016-10-16 19:22
So assuming that `http://clojars.org/repo/feed.clj.gz` is the feed mentioned here, I cannot reproduce. Here is the `core.matrix` entry on the feed:
```
{:group-id "net.mikera", :artifact-id "core.matrix", :description "N-dimensional array programming API for Clojure", :scm {:connection "scm:git:git@github.com:mikera/core.matrix.git", :developer-connection "scm:git:git@github.com:mikera/core.matrix.git", :tag "core.matrix-0.56.0", :url "https://github.com/mikera/core.matrix"}, :homepage "https://github.com/mikera/core.matrix", :url "https://github.com/mikera/core.matrix", :versions ["0.56.0" "0.55.0" "0.54.0" "0.53.0" "0.52.2" "0.52.1" "0.52.0" "0.51.0" "0.50.2" "0.50.1" "0.50.0" "0.49.0" "0.48.0" "0.47.1" "0.47.0" "0.46.0" "0.45.0" "0.44.0" "0.43.0" "0.42.1" "0.42.0" "0.41.0" "0.40.0" "0.39.0" "0.38.0" "0.37.0" "0.36.1" "0.36.0" "0.35.0" "0.34.0" "0.33.2" "0.33.1" "0.33.0" "0.32.1" "0.32.0" "0.31.1" "0.31.0" "0.30.2" "0.30.1" "0.30.0" "0.29.1" "0.29.0" "0.28.0" "0.27.1" "0.27.0" "0.26.0" "0.25.0" "0.24.0" "0.23.0" "0.22.0" "0.21.0" "0.20.0" "0.19.0" "0.18.0" "0.17.0" "0.16.0" "0.15.0" "0.14.0" "0.13.1" "0.13.0" "0.12.0" "0.11.0" "0.10.0" "0.9.0" "0.8.0" "0.7.2" "0.7.1" "0.7.0" "0.6.0" "0.5.0" "0.4.1" "0.4.0" "0.3.0" "0.2.0" "0.1.1" "0.1.0" "0.0.12" "0.0.11" "0.0.10"]}
```
The count of lines that have `group-id` is the same as the whole file.

I suggest to close this issue unless @mikera confirms that this is still an issue and add steps to reproduce.

**Comment by danielcompton** [comment] 2016-10-16 21:35
I've noticed some problems with parsing some of @mikera's POMs, I suspect this may be part of the same issue? But good to get a confirmation if this is still an issue?

**Comment by mikera** [comment] 2016-10-17 06:37
It appears to be fixed in the current clojars, I'm looking at this page:

https://clojars.org/net.mikera/core.matrix/versions

This shows all the versions that I expect. Should I close the issue?

**Comment by danielcompton** [comment] 2016-10-17 07:23
Will close this for now, and reopen if it happens in the future. Thanks!

**Closed by danielcompton** 2016-10-17 07:23 UTC
Labels: bug, hacktoberfest, medium, ready

**Comment by tobias** [comment] 2016-10-26 12:04
I suspect this is no longer an issue because we stopped reading pom files to generate the feed, and generate form data in the DB instead.
