### ISSUE TITLE
Different metadata in Clojars repo and CDN

### ISSUE THREAD

**Issue by glts** [clojars/clojars-web#729] opened 2019-08-23 14:30 UTC
I noticed a difference in metadata at the following URLs:

* https://clojars.org/repo/environ/environ/maven-metadata.xml
* https://repo.clojars.org/environ/environ/maven-metadata.xml

The latest two versions seem to be missing in the CDN metadata. Shouldn’t these files be identical?

I discovered this without looking for it at all, so presumably there are many more such differences.

**Comment by danielcompton** [comment] 2019-08-30 10:31
I think this is a duplicate of #707. The artifacts themselves seem to be in both places, but you're right that the metadata files are not in sync. Closing to continue discussion over there. Thanks for looking into this!

**Closed by danielcompton** 2019-08-30 10:31 UTC
